// react-microfrontend/src/views/MainPage.js
import React from 'react';
import {
  addInitListener,
  removeInitListener
} from '@luigi-project/client';

export default class MainPage extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      message: '',
      url: ''
    };
    this.initListener = null;
    this.contextUpdateListener = null;
  }

  componentDidMount() {
    this.initListener = addInitListener(initialContext => {
      this.setState({
        message: 'Luigi Client initialized.',
        url: window.location.href
      });
    });
  }

  componentWillUnmount() {
    removeInitListener(this.initListener);
  }

  render() {
    return (
      <div>
        <h1>react-microfrontend app is running!</h1>
        <h3>This is main page</h3>
        <br/>
        <p style={{color: 'red'}}>Current Microfrontend URL: <b>{this.state.url}</b></p>
      </div>
    );
  }
}

// angular-microfrontend/src/app/main-page/main-page.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, NavigationEnd, Event as NavigationEvent, Navigation } from '@angular/router';
import { linkManager, getNodeParams, addInitListener } from '@luigi-project/client';

@Component({
  selector: 'app-main-page',
  templateUrl: './main-page.component.html',
  styleUrls: ['./main-page.component.css']
})
export class MainPageComponent implements OnInit {
  private router: Router;

  constructor(router: Router) {
    this.router = router;
   }

  url = window.location.href;

  ngOnInit(): void {
    addInitListener((context) => {
      console.log('Luigi Client initialised in Main Page');
      console.log('nodeParams', getNodeParams());
    });

    
  }
  

}


<div>
      <h1>angular-microfrotend-one main page is running</h1>
    
    <p style="color: red" >Current Microfrontend URL: <b>{{url}}</b></p>
</div>
